#Create user
POST http://127.0.0.1:5000/bank/users/
Content-Type: application/json

{
  "user": "aa",
  "password": "pass"
}


# Create account
POST http://127.0.0.1:5000/bank/users/aa/accounts/
# Deposit
POST http://127.0.0.1:5000/bank/users/aa/accounts/1
Content-Type: application/json
{
  "operation": "deposit",
  "quantity": 3
}

# Get balance
GET http://127.0.0.1:5000/bank/users/aa/accounts/1
# Withdraw
POST http://127.0.0.1:5000/bank/users/aa/accounts/1
Content-Type: application/json
{
  "operation": "withdraw",
  "quantity": 3
}
# Now, we are going to check transfer operation
#Create user
POST http://127.0.0.1:5000/bank/users/
Content-Type: application/json

{
  "user": "bb",
  "password": "pass"
}

# Create new user and account
POST http://127.0.0.1:5000/bank/users/bb/accounts/
# Transfer
POST http://127.0.0.1:5000/bank/users/aa/accounts/1
Content-Type: application/json
{
  "operation": "transfer",
  "quantity": 3,
  "to_user": "bb",
  "to_account": 2
}
# Get other account balance
GET http://127.0.0.1:5000/bank/users/bb/accounts/2